//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitaPaymentService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITradeServerGGJK")]
    public interface ITradeServerGGJK {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITradeServerGGJK/RunService", ReplyAction="http://tempuri.org/ITradeServerGGJK/RunServiceResponse")]
        int RunService(string TradeType, string TradeMsg, ref string TradeOut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITradeServerGGJKChannel : HospitaPaymentService.ServiceReference1.ITradeServerGGJK, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TradeServerGGJKClient : System.ServiceModel.ClientBase<HospitaPaymentService.ServiceReference1.ITradeServerGGJK>, HospitaPaymentService.ServiceReference1.ITradeServerGGJK {
        
        public TradeServerGGJKClient() {
        }
        
        public TradeServerGGJKClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TradeServerGGJKClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradeServerGGJKClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TradeServerGGJKClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RunService(string TradeType, string TradeMsg, ref string TradeOut) {
            return base.Channel.RunService(TradeType, TradeMsg, ref TradeOut);
        }
    }
}
